### ISSUE TITLE
Exception thrown when processing OpHitFinder at reco stage 1 for nue+cosmic overlay sample (seen in v09_09_00 and v09_08_00)

### ISSUE THREAD

**Issue by mayawos** [SBNSoftware/icaruscode#94] opened 2020-11-02 14:44 UTC
@wesketchum @SFBayLaser @PetrilloAtWork @jzennamo 

I'm seeing failures related to the nue+cosmic overlay sample when processing reco stage 1 files, and the mode of failures are seen both in icaruscode v09_08_00 and v09_09_00.

I tried to reproduce the issue interactively but the job was killed when ran in icarusgpvm machines. The command to reproduce this issue was:

`lar -c reco_icarus_driver_reco_multitpc_gauss_sce.fcl -s /pnfs/icarus/scratch/users/icaruspro/dropbox/mc1/poms_test/2020A_00_poms_icarus_prod_BNB_nue_cosmic_v09_09_00/detsim/gen-prodcorsika_genie_nooverburden_icarus_Oct2020_nue_20201031T175123_1-0008_gen_20201031T180247_filter_20201031T213313_g4_20201101T162313_detsim.root `

The failure mode:

```
TrigReport ---------- Event  Summary ------------
TrigReport Events total = 14 passed = 13 failed = 1

TrigReport ------ Modules in End-Path: end_path ------------
TrigReport  Trig Bit#        Run    Success      Error Name
TrigReport     0    0         13         13          0 out1

TimeReport ---------- Time  Summary ---[sec]----
TimeReport CPU = 3409.088455 Real = 3708.123215

MemReport  ---------- Memory  Summary ---[base-10 MB]----
MemReport  VmPeak = 8394.31 VmHWM = 7346.54

%MSG-s ArtException:  PostEndJob 02-Nov-2020 13:05:32 UTC ModuleEndJob
---- EventProcessorFailure BEGIN
  EventProcessor: an exception occurred during current event processing
  ---- ScheduleExecutionFailure BEGIN
    Path: ProcessingStopped.
    ---- StdException BEGIN
      An exception was thrown while processing module OpHitFinder/ophit run: 1 subRun: 8 event: 31
      std::exception
    ---- StdException END
    Exception going through path reco
  ---- ScheduleExecutionFailure END
---- EventProcessorFailure END
---- FatalRootError BEGIN
  Fatal Root Error: TTree::SetEntries
  Tree branches have different numbers of entries, eg anab::T0recob::PFParticlevoidart::Assns_pandoraGausSCECryo0__McRecoGauss. has 13 entries while EventAuxiliary has 45 entries.
  ROOT severity: 2000
---- FatalRootError END
%MSG
Art has completed and will exit with status 1.
trying to exit 1
Mon Nov 2 13:05:33 UTC 2020 fife_wrap COMPLETED with exit status 1
```

**Comment by wesketchum** [comment] 2020-11-02 15:14
I expect the job was killed on the gpvms due to memory issues. Likely it's reproducible the on one of the build machines (will try to check in a bit)

**Comment by jzennamo** [comment] 2020-11-05 18:25
Poking @cfarnese and @mstancar since this is of interest to them

**Comment by jzennamo** [comment] 2020-11-05 18:30
also @ggamezdiego

**Comment by SFBayLaser** [comment] 2020-11-05 20:30
I understand that Gianluca is looking at it right now.

Sent from my iPhone X

On Nov 5, 2020, at 11:30 AM, jzennamo <notifications@github.com> wrote:

﻿

also @ggamezdiego<https://github.com/ggamezdiego>

**Comment by PetrilloAtWork** [comment] 2020-11-05 21:11
I **can** reproduce the issue running only `ophit` module instance, and only on the 14th event (`--nskip 13`).
```
[ERROR] Logic error! Negative buffer_num_index...
```
is probably the key message.

**Comment by PetrilloAtWork** [comment] 2020-11-06 02:27
I have patched the code so that this issue should not occur any more.
The patch is in `larana`.
**But** a fundamental issue here is that the algorithm is not properly tuned for this simulation yet.
Users of the sample should have that clear in mind.

SLAC optical reconstruction people (@drinkingkazu , @Temigo , François Drielsma whose GitHub account I apparently can't find) are welcome to take a look and comment.

## The issue in detail

This is a sliding time window hit finding algorithm based on thresholds.
Each hit is assigned some pre-buffer time and also a post-buffer time; specific logic guarantees that the prebuffer of a hit does not leak into the previous hit, including the post-buffer.
If when a new hit starts the previous hit is still in its "post-buffer", the previous hit range is truncated to one sample before the start of the prebuffer of the new hit. In this corner case, the hit starts on the very first sample (`i = 0`), but it's actually just a fluctuation (or maybe the tail of previous non-triggering activity) and the hit ends immediately, so that sample `i = 1` is post-buffer already.
Soon after, sample `i=4` starts a new hit, and `i = 4` sample would belong to the previous hit. Given that the prebuffer is configured to be 5 samples, the new hit is going to start at `i = 0` (should be `i = -1`, but the prebuffer is adjusted for sanity).
The previous hit is truncated to the sample before the start, which should be `i = -1`, and this time sanity is not checked, yielding to a hit ending at a non-existing sample (which by signed/unsigned joggling becomes a large number, but that's just ripples from the real issue).
My patch is just ensuring that the end of the previous hit is not negative; this may still result in a candidate hit with non-positive width, which the code would immediately reject.

**Comment by wesketchum** [comment] 2020-11-11 17:21
@PetrilloAtWork is this done/good to close with this week's larana?

**Comment by SFBayLaser** [comment] 2020-11-13 16:52
This issue should now be fixed with LArSoft v09_09_02 so will close...

**Closed by SFBayLaser** 2020-11-13 16:52 UTC
Labels: bug
