### ISSUE TITLE
Jobs failed at the reco 1 stage when using reco_icarus_driver_reco_multitpc_gauss_sce.fcl/reco_icarus_driver_reco_multitpc_gauss.fcl

### ISSUE THREAD

**Issue by mayawos** [SBNSoftware/icaruscode#92] opened 2020-10-28 13:41 UTC
I'm seeing jobs failures at the reco1 stage when using the `reco_icarus_driver_reco_multitpc_gauss_sce.fcl`/` reco_icarus_driver_reco_multitpc_gauss.fcl`

```
MultiPandoraApiImpl::DeletePandoraInstances - unable to find daughter instances associated with primary 0
%MSG-s ArtException:  PostEndJob 28-Oct-2020 08:43:39 UTC ModuleEndJob
---- Unknown BEGIN
  An unknown exception was thrown while processing module StandardPandora/pandoraGausCryo0 during beginJob
---- Unknown END
%MSG
```

The issue is also seen when running interactive session, e.g.
` lar -c reco_icarus_driver_reco_multitpc_gauss_sce.fcl -s /pnfs/icarus/scratch/users/icaruspro/dropbox/mc1/poms_test/MCC1_poms_icarus_prod_BNB_nue_v09_08_00/detsim/gen-simulation_genie_icarus_Mar2019_nue_20201027T183455_1-0001_gen_20201027T192247_filter_20201027T194936_g4_20201027T214801_detsim.root`

**Comment by wesketchum** [comment] 2020-10-28 17:35
@cfarnese @PetrilloAtWork @jzennamo @brucehoward-physics  Pinging a few other people here, just to draw attention. Maya also reports this is failing in other samples, so seems to be a common across-board problem.

**Comment by PetrilloAtWork** [comment] 2020-10-28 19:11
```
Unable to find file  PandoraBdt_v08_33_00_SBND.xml in any path specified by environment variable FW_SEARCH_PATH, delimiter :
Failure in reading pandora settings, STATUS_CODE_NOT_FOUND
PandoraApi::ReadSettings(*m_pPrimaryPandora, fullConfigFileName) throw STATUS_CODE_FAILURE
    in function: ConfigurePandoraInstances
    in file:     /scratch/workspace/build-larsoft/BUILDTYPE/debug/QUAL/s102-e19/label1/swarm/label2/SLF7/build/larpandora/v09_03_00-buildFW/src/larpandora/LArPandoraInterface/StandardPandora_module.cc line#: 114
```
Do we need a `PandoraBdt_v08_33_00_SBND.xml` in ICARUS?

**Comment by brucehoward-physics** [comment] 2020-10-28 20:59
These XMLs are for the Pandora MVA tools. They live in "PandoraMVAs" directory in icarus_data. Gianluca found that the XMLs existed in the directory, but that there was no entry in CMakeList for this directory.

I did have the magic line in my ups/product_deps for

set_fwdir  product_dir  icarus_data/PandoraMVAs

and things ran when I tested them in my test release.

Does that not work for base releases or certain ways of setting things up but does work for others or something? Apologies for forgetting to add the directory to CMakeLists.

**Comment by PetrilloAtWork** [comment] 2020-10-28 21:48
Right now the problem is that those XML files are not distributed with `icarus_data` release.
@mayawos, could you advise on which kind of solution is acceptable?
My understanding is that the interim release manager, @SFBayLaser, is not available these days, so a new release of `icarus_data` is maybe not possible.
Possibilities include:
* storing the missing files somewhere already included in the `FW_SEARCH_PATH` of the execution environment (which is...?)
* storing the missing files somewhere else and have your environment (`FW_SEARCH_PATH`) include that location
* major hack: add those files in the CVMFS copy of `icarus_data` (if `icarus_data` release is downloaded from SciSoft this won't work)

**Comment by PetrilloAtWork** [comment] 2020-10-28 21:51
Also note that, in general, lines like `set_fwdir product_dir icarus_data/PandoraMVAs` are usually not necessary, if you can specify a path in your code (which you usually can): having `PandoraBdt_v08_33_00_SBND.xml` in your configuration with `set_fwdir product_dir icarus_data/PandoraMVAs` is equivalent to having `PandoraMVAs/PandoraBdt_v08_33_00_SBND.xml` in your configuration (that is because there is already a `set_fwdir product_dir icarus_data` in `icarus_data`).

**Comment by brucehoward-physics** [comment] 2020-10-28 21:53
Yeah, I just thought it was a little nicer solution than specifying the directory path too. But the magic lines hid that the CMakeList wasn't updated... Dang. I'm sorry :(

**Comment by brucehoward-physics** [comment] 2020-10-28 21:57
As a temporary work-around using point 1 in Gianluca's set of ideas, I want to say that probably the path with the PandoraSettings_*_ICARUS.xml files are in the `FW_SEARCH_PATH`? I think it's:

`icaruscode/TPC/Tracking/ICARUSPandora/scripts/`

That might be a good temporary place to check.

**Comment by brucehoward-physics** [comment] 2020-10-28 22:00
Unless you need something outside of `icaruscode` as well. Sorry @PetrilloAtWork,  it just occurred to me what you might have meant by "execution environment"

**Comment by PetrilloAtWork** [comment] 2020-10-28 22:03
What we are looking for in option 1 is an absolute path configured in `FW_SEARCH_PATH`, that is accessible from the worker node and that we have writing access to.
An example may be a StashCache directory (e.g. `/pnfs/icarus/persistent/stash/icaruspro` or `/pnfs/icarus/persistent/numiflux_sample`, which is not a good choice for obvious reasons ;-) ).

**Comment by PetrilloAtWork** [comment] 2020-10-28 22:28
I see that the jobs I submit via `project.py` have no PNFS not StashCache path. Maybe POMS is different?

**Comment by mayawos** [comment] 2020-10-29 02:05
@PetrilloAtWork thanks for looking into this. I think solution #2 is the easiest to implement. I can copy the the `PandoraBdt_v08_33_00_SBND.xml` to the`/pnfs/icarus/resilient` area. When submitting the jobs, this file will be copied to the worker node on the grid. I just need to add the `$CONDOR_DIR_INPUT` in the `FW_SEARCH_PATH` inside POMS configuration.

**Comment by PetrilloAtWork** [comment] 2020-10-29 05:03
In that case, make sure you copy both the missing files, just in case.
You can see them in [Redmine](https://cdcvs.fnal.gov/redmine/projects/icarus_data/repository/show/icarus_data/PandoraMVAs?rev=feature%2Fhoward_pandorashower_october2020prod), or in any `icarus_data` with branch `feature/howard_pandorashower_october2020prod` checked out at the directory `icarus_data/PandoraMVAs`.
Judging from the way the files are mentioned in Pandora's XML  (e.g. [`icaruscode/TPC/Tracking/ICARUSPandora/scripts/PandoraSettings_Master_ICARUS.xml`](https://github.com/SBNSoftware/icaruscode/blob/d16b878f1c1992391ad48f5aa0fbd3b71048a4b5/icaruscode/TPC/Tracking/ICARUSPandora/scripts/PandoraSettings_Master_ICARUS.xml#L37)), it looks like if the directory you set things in is e.g. `/pnfs/icarus/resilient/icaruspro/icarus_data/v09_08_00/icarus_data/PandoraMVAs/PandoraBdt_v08_33_00_SBND.xml`, then the directory in `FW_SEARCH_PATH` should be `/pnfs/icarus/resilient/icaruspro/icarus_data/v09_08_00/icarus_data/PandoraMVAs`.

**Comment by mayawos** [comment] 2020-10-29 14:03
These are the 2 files I see listed under` icarus_data/PandoraMVAs` in `feature/howard_pandorashower_october2020prod`

```
ls -1 PandoraMVAs/*.xml
PandoraMVAs/PandoraBdt_v08_33_00_SBND.xml
PandoraMVAs/PandoraBdt_v08_43_00_ICARUS_vertex_bnb.xml
```

I copied both of these files to the grid node and changed the `FW_SEARCH_PATH` to scan the grid node where the files are being copied to.

Re-ran the reco1 stage using the same detsim input and looks like it's working. i.e. completed jobs exit with code 0 and producing reco1 output files.

**Comment by wesketchum** [comment] 2020-10-29 16:40
So, that seems like it will get things working. But with respect to a new release ... these should get into `icarus_data`? Or someplace else?

**Comment by brucehoward-physics** [comment] 2020-10-29 16:56
The two XMLs are in a sub-folder of `icarus_data` already but CMakeLists.txt in the top-level of `icarus_data` isn't set up to

add_subdirectory(PandoraMVAs)

It should also be checked if the CMakeLists.txt in the `PandoraMVAs` directory is sufficient or if further lines need to be present to install the XMLs in a proper way to be used by the base release.

Does `set_fwdir` not work at all with the base release, or is it just that if `add_subdirectory()` isn't there, then the base release won't even have the directory to point to from `set_fwdir`? If it's the former then further tiny changes are needed in `icaruscode` to get the file path right. If it's the latter, then I think just the first paragraph is sufficient. In that case, I guess I just got lucky in my tests because I tested with `mrbsetenv`/`mrb install` and not `mrbslp`?

**Comment by wesketchum** [comment] 2020-10-29 18:13
I think the latter sounds more right?

I will be working on a release, and will explicitly test with Maya's command above outside an mrb build environment, just to make sure it works.

Thanks for the clarification.

**Comment by SFBayLaser** [comment] 2020-10-30 14:38
I have updated the CMakeLists.txt file to include the pandora MVAs in the release. Package is tagged and will be in the upcoming release (v09_09_00)

**Comment by wesketchum** [comment] 2020-10-30 22:07
I'm still getting this error in v09_09_00

```
%MSG-s ArtException:  PostEndJob 30-Oct-2020 17:04:36 CDT ModuleEndJob
---- Unknown BEGIN
  An unknown exception was thrown while processing module StandardPandora/pandoraGausCryo0 during beginJob
---- Unknown END
%MSG
```

**Comment by brucehoward-physics** [comment] 2020-10-31 00:19
Now without the complaint about the files I added I assume?

**Comment by brucehoward-physics** [comment] 2020-10-31 22:20
I checked and I'm getting the XML files not found in v09_09 as well. I see that the icarus_data version is bumped up to v09_09 but the XML files are not present

[icarusgpvm03.fnal.gov@test-v09_09]$ ls $ICARUS_DATA_DIR/icarus_data/
CRT  FlashMatch  Generator  PhotonLibrary  Responses  SCEoffsets  WirecellData

PandoraMVAs directory is not present

**Comment by mayawos** [comment] 2020-11-02 14:47
Just an update. I keep the workaround I had for v09_08_00 (copying the xml files to the worker node and adding the worker node location to the `FW_SEARCH_PATH`) and the production jobs was able to run in v09_09_00.

**Comment by brucehoward-physics** [comment] 2020-11-03 18:48
For what it's worth, I think what's missing still is just fixing the line in `icarus_data/PandoraMVAs/CMakeLists.txt` to be `file(GLOB data *.xml )` so that the xml files are installed.

**Comment by SFBayLaser** [comment] 2020-11-13 16:40
I believe this week's release (v09_09_02) resolves this issue so am closing.

**Closed by SFBayLaser** 2020-11-13 16:40 UTC
Labels: bug
